-- Estructura base de datos del servicio academico (Parte 2).
-- Escrita en H2 modo Oracle. En Oracle 12c+ las secuencias se reemplazarian
-- por columnas GENERATED BY DEFAULT AS IDENTITY; aqui se modelan como
-- SEQUENCE explicitas para que la migracion a Oracle real sea directa.

CREATE SEQUENCE IF NOT EXISTS seq_enrollment START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS seq_grade START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS seq_audit_log START WITH 1 INCREMENT BY 1;

-- Student: subconjunto minimo de datos personales. En la arquitectura de
-- Parte 1, la fuente de verdad de este dato es el Sistema Academico externo;
-- aqui se modela localmente porque este servicio es la implementacion de
-- referencia autocontenida de ese "Adaptador Academico".
CREATE TABLE IF NOT EXISTS student (
    student_id      VARCHAR(20)   NOT NULL PRIMARY KEY,
    full_name       VARCHAR(150)  NOT NULL,
    document_id     VARCHAR(30)   NOT NULL
);

CREATE TABLE IF NOT EXISTS course (
    course_code     VARCHAR(20)   NOT NULL PRIMARY KEY,
    course_name     VARCHAR(150)  NOT NULL,
    credits         INTEGER       NOT NULL
);

-- term se modela como VARCHAR suelto (ej. '2026-2') y no como entidad propia
-- ACADEMIC_TERM: simplificacion deliberada para el alcance de 3h, igual que
-- la simplificacion ya declarada para GRADE/ENROLLMENT autocontenidas.
CREATE TABLE IF NOT EXISTS enrollment (
    enrollment_id   BIGINT        NOT NULL PRIMARY KEY,
    student_id      VARCHAR(20)   NOT NULL,
    course_code     VARCHAR(20)   NOT NULL,
    term            VARCHAR(10)   NOT NULL,
    group_code      VARCHAR(10)   NOT NULL,
    status          VARCHAR(20)   NOT NULL, -- ENROLLED, WITHDRAWN, PASSED, FAILED
    CONSTRAINT fk_enrollment_student FOREIGN KEY (student_id) REFERENCES student (student_id),
    CONSTRAINT fk_enrollment_course FOREIGN KEY (course_code) REFERENCES course (course_code)
);

CREATE TABLE IF NOT EXISTS grade (
    grade_id        BIGINT        NOT NULL PRIMARY KEY,
    enrollment_id   BIGINT        NOT NULL,
    assessment      VARCHAR(30)   NOT NULL, -- MIDTERM_1, MIDTERM_2, FINAL...
    score           DECIMAL(3,1)  NOT NULL,
    recorded_date   DATE          NOT NULL,
    CONSTRAINT fk_grade_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollment (enrollment_id)
);

-- Dato nuevo de negocio propio de Vista 360 (no existe en ningun sistema
-- fuente): que estudiantes tiene asignados cada acompanante academico. La
-- autorizacion de un rol ADVISOR para consultar a un estudiante se valida
-- SIEMPRE contra esta tabla en el servicio, nunca confiando en un claim del JWT.
CREATE TABLE IF NOT EXISTS advisor_assignment (
    advisor_id      VARCHAR(20)   NOT NULL,
    student_id      VARCHAR(20)   NOT NULL,
    PRIMARY KEY (advisor_id, student_id),
    CONSTRAINT fk_assignment_student FOREIGN KEY (student_id) REFERENCES student (student_id)
);

-- Bitacora de auditoria de LECTURAS (no solo escrituras) sobre datos de
-- estudiante. Es lo que permite responder "con certeza" un reclamo de acceso
-- indebido (Parte 4, escenario B): quien consulto que estudiante, cuando,
-- con que rol y bajo que correlation-id de request.
CREATE TABLE IF NOT EXISTS audit_log (
    audit_id         BIGINT        NOT NULL PRIMARY KEY,
    actor_id         VARCHAR(20)   NOT NULL, -- quien hizo la consulta (studentId o advisorId)
    actor_role       VARCHAR(20)   NOT NULL,
    student_id       VARCHAR(20)   NOT NULL, -- estudiante consultado
    action           VARCHAR(40)   NOT NULL, -- GET_COURSES_AND_GRADES
    result           VARCHAR(20)   NOT NULL, -- ALLOWED, DENIED, NOT_FOUND
    correlation_id   VARCHAR(60),
    occurred_at      TIMESTAMP     NOT NULL
);
